"""Pipeline floor: complete CFD velocity through the shared post-processing, all nine diseased cases.

Run from the repository root:
    python scripts/manuscript/generate_reference_table.py
Reads the ``cfd`` run records (report/metrics/reconstruction/runs/rev2_cfd_*.json).
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANUSCRIPT = ROOT / "paper/revision_2026_09/manuscript"


def main() -> None:
    """Regenerate manuscript outputs from retained inputs."""
    (MANUSCRIPT / "figures/generated").mkdir(parents=True, exist_ok=True)
    (MANUSCRIPT / "tables").mkdir(parents=True, exist_ok=True)
    (ROOT / "report/tables").mkdir(parents=True, exist_ok=True)
    recs = {}
    for p in sorted(
        (ROOT / "report/metrics/reconstruction/runs").glob("rev2_cfd_c*_g2.5_s0.json")
    ):
        r = json.loads(p.read_text())
        recs[(r["problem"]["case"], r["problem"]["target_ms"])] = r
    forms = ("unsteady+mut", "steady+mut", "unsteady+lam", "steady+lam")
    rows = []
    for case in range(1, 10):
        for t, ph in ((1780, "Sys."), (2400, "Dia.")):
            r = recs[(case, t)]
            cells = [f"{r['pressure'][f]['p_rel_l2']:.3f}" for f in forms]
            cells += [
                f"{r['pressure']['unsteady+mut']['dp_cfd_Pa']:.1f}",
                f"{r['wss_h_sweep_oracle']['0.1']:.3f}",
                f"{r['wss']['wss_mag_rel_l2']:.3f}",
            ]
            rows.append(" & ".join([str(case), ph] + cells) + r" \\")
    tex = (
        r"""% Generated by generate_reference_table.py from the cfd run records.
\begin{table}[htbp]
\centering
\small
\setlength{\tabcolsep}{4pt}
\caption{Pipeline floor, obtained by passing the complete CFD velocity through the shared post-processing. Pressure columns give the sub-cloud relative L2 error for each information setting (time term on or off; CFD eddy viscosity or molecular viscosity only). $\Delta p_{\rm sub}$ is the CFD pressure drop between the inlet and outlet ends of the sub-cloud. Wall-shear columns give the aneurysm-zone magnitude error of the one-sided estimate at $h=0.1$~mm and at the registered $h=0.25$~mm. Case 2's systolic window runs forward from the target (1.780--1.788~s), which explains its larger unsteady error.}
\label{tab:reference_floor}
\begin{tabular}{llccccrcc}
\toprule
 & & \multicolumn{4}{c}{Pressure relative L2} & & \multicolumn{2}{c}{Wall shear} \\
\cmidrule(lr){3-6}\cmidrule(lr){8-9}
Case & Phase & Unst.+$\mu_t$ & Steady+$\mu_t$ & Unst.+$\mu$ & Steady+$\mu$ & $\Delta p_{\rm sub}$ (Pa) & $h=0.1$ & $h=0.25$ \\
\midrule
"""
        + "\n".join(rows)
        + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    )
    (MANUSCRIPT / "tables/reference_floor.tex").write_text(tex, encoding="utf-8")
    print(tex)


if __name__ == "__main__":
    main()
