"""Robustness of the confirmation to the interpolation comparator (draw 0, 2.5 mm, Cases 2-8).

Run from the repository root after the rbf_tuned / rbf_spacetime records are in
report/metrics/reconstruction/runs:
    python scripts/manuscript/generate_robustness_table.py
"""

import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
MANUSCRIPT = ROOT / "paper/revision_2026_09/manuscript"
RUNS = ROOT / "report/metrics/reconstruction/runs"
P, W, V = (
    ("pressure", "unsteady+mut", "p_rel_l2"),
    ("wss", "wss_mag_rel_l2"),
    ("velocity", "vel_rel_l2"),
)


def get(r, path):
    for k in path:
        r = r[k]
    return float(r)


def rec(name):
    f = RUNS / f"{name}.json"
    return json.loads(f.read_text()) if f.exists() else None


def write_completed_groups(methods, data, units) -> None:
    """Report only method/phase groups with all seven cases; mark gaps explicitly."""
    rows = []
    groups = []
    for target, phase in ((1780, "Systole"), (2400, "Diastole")):
        phase_units = [unit for unit in units if unit[1] == target]
        for method, label, _ in methods:
            missing = [
                case for case, time in phase_units if data[method][(case, time)] is None
            ]
            group = {"method": method, "target_ms": target, "missing_cases": missing}
            if missing:
                cells = [r"\multicolumn{3}{c}{Pending: incomplete case coverage}"]
            else:
                values = {
                    key: float(
                        np.median([get(data[method][u], path) for u in phase_units])
                    )
                    for key, path in (("velocity", V), ("pressure", P), ("wss", W))
                }
                group["median_errors"] = values
                group["continuity_wins"] = {
                    key: sum(
                        get(data["cont"][u], path) < get(data[method][u], path)
                        for u in phase_units
                    )
                    for key, path in (("velocity", V), ("pressure", P), ("wss", W))
                }
                cells = [f"{value:.3f}" for value in values.values()]
            groups.append(group)
            rows.append(" & ".join([phase, label] + cells) + r" \\")
    tex = (
        r"""% Generated by generate_robustness_table.py --completed-groups.
\begin{table}[htbp]
\centering
\small
\caption{Robustness checks at 2.5~mm using draw 0. Each numerical row is the median over all seven confirmation cases (Cases~2--8); an incomplete method--phase group is left pending rather than summarized over fewer cases. Pressure uses the unsteady calculation with CFD-supplied eddy viscosity, and wall shear uses $h=0.25$~mm. These post hoc checks are separate from the three-draw primary comparison.}
\label{tab:robustness_completed}
\begin{tabular}{llccc}
\toprule
Phase & Method & Velocity & Pressure & WSS \\
\midrule
"""
        + "\n".join(rows)
        + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    )
    (MANUSCRIPT / "tables/robustness_completed.tex").write_text(tex, encoding="utf-8")
    summary = {"status": "interim", "cases_per_group": 7, "seed": 0, "groups": groups}
    (ROOT / "report/tables/eacfm_robustness_completed.json").write_text(
        json.dumps(summary, indent=2), encoding="utf-8"
    )
    print(json.dumps(summary, indent=2))


def main(completed_groups: bool = False) -> None:
    """Regenerate manuscript outputs from retained inputs."""
    (MANUSCRIPT / "figures/generated").mkdir(parents=True, exist_ok=True)
    (MANUSCRIPT / "tables").mkdir(parents=True, exist_ok=True)
    (ROOT / "report/tables").mkdir(parents=True, exist_ok=True)
    methods = [
        (
            "cont",
            "Continuity field",
            lambda c, t: f"rev2_cont_oracle_c{c:02d}_t{t}_g2.5_s0_i0_w0.01",
        ),
        ("rbf", "RBF (registered)", lambda c, t: f"rev2_rbf_c{c:02d}_t{t}_g2.5_s0"),
        (
            "rbf_tuned",
            "RBF (tuned)",
            lambda c, t: f"rev2_rbf_tuned_c{c:02d}_t{t}_g2.5_s0",
        ),
        (
            "rbf_spacetime",
            "RBF (space-time)",
            lambda c, t: f"rev2_rbf_spacetime_c{c:02d}_t{t}_g2.5_s0",
        ),
    ]
    units = [(c, t) for c in range(2, 9) for t in (1780, 2400)]
    data = {m: {u: rec(fn(*u)) for u in units} for m, _, fn in methods}
    complete = [u for u in units if all(data[m][u] is not None for m, _, _ in methods)]
    if completed_groups:
        write_completed_groups(methods, data, units)
        return
    if len(complete) != len(units):
        missing = sorted(set(units) - set(complete))
        raise ValueError(
            f"Incomplete robustness coverage; missing case/time units: {missing}"
        )
    print(f"{len(complete)}/{len(units)} units complete")

    rows, summary = [], {"n_units": len(complete)}
    for t, phase in ((1780, "Systole"), (2400, "Diastole")):
        us = [u for u in complete if u[1] == t]
        for m, label, _ in methods:
            cells = [
                f"{np.median([get(data[m][u], path) for u in us]):.3f}"
                for path in (V, P, W)
            ]
            rows.append(" & ".join([phase, label] + cells) + r" \\")
    for m, _, _ in methods[2:]:
        best = {}
        for key, path in (("pressure", P), ("wss", W), ("velocity", V)):
            wins = sum(
                get(data["cont"][u], path) < get(data[m][u], path) for u in complete
            )
            ratio = float(
                np.median(
                    [
                        get(data["cont"][u], path) / get(data[m][u], path)
                        for u in complete
                    ]
                )
            )
            best[key] = {"cont_wins": int(wins), "median_ratio_cont_over": ratio}
        summary[m] = best
        # strongest comparator per unit: min over the three RBF variants
    for key, path in (("pressure", P), ("wss", W), ("velocity", V)):
        wins = sum(
            get(data["cont"][u], path)
            < min(get(data[m][u], path) for m, _, _ in methods[1:])
            for u in complete
        )
        summary.setdefault("best_rbf_per_unit", {})[key] = int(wins)
    summary["selected"] = {
        f"{u[0]}_{u[1]}": {
            m: {
                k: data[m][u].get(k)
                for k in ("kernel", "neighbors", "smoothing", "time_scale_m_per_s")
                if k in data[m][u]
            }
            for m in ("rbf_tuned", "rbf_spacetime")
        }
        for u in complete
    }
    print(json.dumps(summary, indent=1))
    (ROOT / "report/tables/eacfm_robustness.json").write_text(
        json.dumps(summary, indent=1)
    )
    tex = (
        (
            r"""% Generated by generate_robustness_table.py.
\begin{table}[htbp]
\centering
\small
\caption{Robustness to the interpolation comparator, given as median relative errors over the UNIT_COUNT case--phase units of Cases~2--8 with draw 0 at 2.5~mm. The tuned RBF chooses kernel, neighbourhood and smoothing on the withheld observations; the space-time RBF interpolates both snapshots jointly with a time scale chosen the same way. All methods share the post-processing; pressure uses the unsteady form with oracle $\mu_t$.}
\label{tab:robustness}
\begin{tabular}{llccc}
\toprule
Phase & Method & Velocity & Pressure & WSS \\
\midrule
""".replace("UNIT_COUNT", str(len(complete)))
        )
        + "\n".join(rows)
        + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    )
    (MANUSCRIPT / "tables/robustness.tex").write_text(tex, encoding="utf-8")


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--completed-groups",
        action="store_true",
        help="Write an explicitly interim table of complete seven-case groups",
    )
    main(parser.parse_args().completed_groups)
