"""Maximum principal stress on the inner wall surface of the dilation segment, all twelve cases.

Run from the repository root:
    python scripts/manuscript/generate_mps.py

Input: the ANSYS Mechanical node exports in data/raw/MPS (tab-separated: node, x, y, z, MPS in Pa).
The aneurysmal exports hold the inner surface of the aneurysm zone; the control exports hold the whole
solid, from which the inner surface is taken as the nodes within 0.4 mm of the fluid wall. The wall is
unwrapped about the axis of the descending branch as in generate_wss_montage.py, restricted to the
dilation segment of each inlet diameter. Outputs figures/generated/mps_montage.{pdf,png} and
tables/mps_summary.tex; the sac body is the middle third of the segment and the necks its outer thirds.
"""

import sys
from pathlib import Path

import matplotlib
import numpy as np
import pandas as pd
from scipy.spatial import cKDTree

matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parents[2]
MANUSCRIPT = ROOT / "paper/revision_2026_09/manuscript"
MPS_DIR = ROOT / "data/raw/MPS"
sys.path.insert(0, str(ROOT))
from idealaorta_pinn.data.full_export import load_block

ROWS = {2.0: (1, 2, 3, 10), 2.3: (4, 5, 6, 11), 2.6: (7, 8, 9, 12)}
COLS = ("axisymmetric", "anterior-dominant", "posterior-dominant", "control")
AXI = {2.0: 1, 2.3: 4, 2.6: 7}
INNER_MM = 0.4


def read_mps(case: int) -> np.ndarray:
    """(N, 4) array of x, y, z (m) and MPS (kPa) on the inner wall surface."""
    d = pd.read_csv(MPS_DIR / f"Case {case}.xls", sep="\t")
    X = d.iloc[:, 1:4].to_numpy(float)
    s = d.iloc[:, 4].to_numpy(float) / 1e3
    W = np.vstack([b[["x", "y", "z"]].to_numpy() for b in (load_block(case, "aneurysm", 1780), load_block(case, "wall", 1780))
                   if b is not None])
    inner = cKDTree(W).query(X)[0] < INNER_MM * 1e-3
    return np.column_stack([X[inner], s[inner]])


def segment_bounds(d: float):
    a = load_block(AXI[d], "aneurysm", 1780)
    return float(a["x"].min()), float(a["x"].max())


def on_segment(w: np.ndarray, x0: float, x1: float, pad: float = 0.01) -> np.ndarray:
    keep = (w[:, 0] >= x0 - pad) & (w[:, 0] <= x1 + pad) & ((w[:, 0] > 0.001) | (w[:, 1] > 0.0155))
    return w[keep]


def montage(data: dict) -> None:
    plt.rcParams.update({"font.size": 7.5, "axes.titlesize": 7.5, "axes.labelsize": 7.5,
                         "xtick.labelsize": 7, "ytick.labelsize": 7, "pdf.fonttype": 42})
    fig, axes = plt.subplots(3, 4, figsize=(6.6, 4.6), sharey=True, layout="constrained")
    norm = plt.Normalize(40, 110)
    for r, (d, cases) in enumerate(ROWS.items()):
        x0, x1 = segment_bounds(d)
        for c_i, case in enumerate(cases):
            w = on_segment(data[case], x0, x1)
            theta = np.degrees(np.arctan2(w[:, 2], w[:, 1] - 0.030))
            ax = axes[r, c_i]
            im = ax.scatter(w[:, 0] * 1e3, theta, c=w[:, 3], s=0.3, cmap="turbo", norm=norm, rasterized=True)
            ax.set(xlim=((x0 - 0.01) * 1e3, (x1 + 0.01) * 1e3), ylim=(-180, 180), yticks=[-180, -90, 0, 90, 180])
            ax.set_title(f"Case {case}" + (f"\n{COLS[c_i]}" if r == 0 else ""), fontsize=7.5)
            if r == 2:
                ax.set_xlabel("x (mm)")
            if c_i == 0:
                ax.set_ylabel(f"$D_{{in}}$ = {d} cm\nangle (deg)")
    cb = fig.colorbar(im, ax=axes, orientation="horizontal", shrink=0.5, pad=0.02, extend="both")
    cb.set_label("maximum principal stress on the inner wall surface (kPa)")
    out = MANUSCRIPT / "figures/generated" / "mps_montage"
    fig.savefig(out.with_suffix(".pdf"))
    fig.savefig(out.with_suffix(".png"), dpi=170)
    plt.close(fig)
    print("saved", out)


def table(data: dict) -> None:
    morph = {c: COLS[i] for cases in ROWS.values() for i, c in enumerate(cases)}
    rows = []
    for d, cases in ROWS.items():
        x0, x1 = segment_bounds(d)
        for case in cases:
            w = on_segment(data[case], x0, x1, pad=0.0)
            s, th = w[:, 3], np.degrees(np.arctan2(w[:, 2], w[:, 1] - 0.030))
            body = (w[:, 0] > x0 + (x1 - x0) / 3) & (w[:, 0] < x1 - (x1 - x0) / 3)
            ant, post = s[body & (np.abs(th) < 60)], s[body & (np.abs(th) > 120)]
            necks = s[~body]
            rows.append(f"{case} & {d:.1f} & {morph[case]} & {np.median(s):.1f} & {np.percentile(s, 95):.1f} & "
                        f"{np.median(ant):.1f} & {np.median(post):.1f} & {np.percentile(necks, 95):.1f} \\\\")
            print(rows[-1])
    head = [
        "% Generated by scripts/manuscript/generate_mps.py from data/raw/MPS.",
        r"\begin{table}[htbp]", r"\centering", r"\small",
        r"\caption{Maximum principal stress (kPa) on the inner wall surface of the dilation segment. Sac-body "
        r"medians use the middle third of the segment, within $60^\circ$ of the anterior or posterior direction; "
        r"the neck value is the 95th percentile over the outer thirds.}",
        r"\label{tab:mps}", r"\begin{tabular}{cclccccc}", r"\toprule",
        r" & & & \multicolumn{2}{c}{Segment} & \multicolumn{2}{c}{Sac body, median} & Necks \\",
        r"\cmidrule(lr){4-5}\cmidrule(lr){6-7}\cmidrule(lr){8-8}",
        r"Case & $D_{\rm in}$ (cm) & Morphology & Median & 95th pct. & Anterior & Posterior & 95th pct. \\",
        r"\midrule",
    ]
    tail = [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    (MANUSCRIPT / "tables/mps_summary.tex").write_text("\n".join(head + rows + tail), encoding="utf-8")


def main() -> None:
    (MANUSCRIPT / "figures/generated").mkdir(parents=True, exist_ok=True)
    data = {case: read_mps(case) for cases in ROWS.values() for case in cases}
    for case, w in data.items():
        print(f"case {case}: {len(w)} inner-surface nodes, MPS max {w[:, 3].max():.1f} kPa")
    montage(data)
    table(data)


if __name__ == "__main__":
    main()
