"""Pilot momentum PINNs scored through the shared post-processing (review: same route for every method).

Reads the continuity-field pilot run records and the ``reconstruct.py diagnose`` outputs of the momentum
PINNs, averages the systolic draws as in the pilot table, and writes tables/pilot_pipeline.tex.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
RUNS = ROOT / "report" / "metrics" / "reconstruction" / "runs"
DIAG = ROOT / "report" / "metrics" / "reconstruction" / "diag"
OUT = ROOT / "paper" / "revision_2026_09" / "manuscript" / "tables" / "pilot_pipeline.tex"
WINDOWS = [(1, 1780, (0, 1)), (1, 2400, (0,)), (9, 1780, (0, 1)), (9, 2400, (0,))]


def stem(arm: str, case: int, t: int, s: int) -> str:
    return f"rev2_{arm}_c{case:02d}_t{t}_g2.5_s{s}_i{s}_w0.01"


def cont(case: int, t: int, seeds) -> tuple[float, float]:
    rs = [json.loads((RUNS / f"{stem('cont_oracle', case, t, s)}.json").read_text()) for s in seeds]
    return (float(np.mean([r["pressure"]["unsteady+mut"]["p_rel_l2"] for r in rs])),
            float(np.mean([r["wss"]["wss_mag_rel_l2"] for r in rs])))


def pinn(arm: str, case: int, t: int, seeds, form: str) -> tuple[float, float]:
    ds = []
    for s in seeds:
        path = DIAG / f"{stem(arm, case, t, s)}.json"
        if not path.exists():
            raise FileNotFoundError(f"run `reconstruct.py diagnose {path.stem}` first")
        ds.append(json.loads(path.read_text()))
    return (float(np.mean([d["pipeline"][form]["p_rel_l2"] for d in ds])),
            float(np.mean([d["pipeline_wss"]["wss_mag_rel_l2"] for d in ds])))


def main() -> None:
    rows = []
    for case, t, seeds in WINDOWS:
        cp, cw = cont(case, t, seeds)
        sp, sw = pinn("steady_oracle", case, t, seeds, "unsteady+mut")
        up, uw = pinn("unsteady_oracle", case, t, seeds, "unsteady+mut")
        us, _ = pinn("unsteady_oracle", case, t, seeds, "steady+mut")
        rows.append(f"{case} & {'Sys.' if t == 1780 else 'Dia.'} & {cp:.3f} & {sp:.3f} & {up:.3f} & {us:.3f} "
                    f"& {cw:.3f} & {sw:.3f} & {uw:.3f} \\\\")
    body = "\n".join(rows)
    OUT.write_text(r"""% Generated by scripts/manuscript/generate_pilot_pipeline.py.
\begin{table}[htbp]
\centering
\small
\caption{Pilot fields scored through the same post-processing. Pressure is the relative L2 error of momentum integration applied to each field's velocity, in the prespecified unsteady form with CFD eddy viscosity, and, for the unsteady PINN, also in the steady form, which does not use the field's time derivative. WSS is the finite-distance estimate at $h=0.25$~mm. All fields use the CFD eddy viscosity. Values are averaged over two draws at systole and one at diastole.}
\label{tab:pilot_pipeline}
\setlength{\tabcolsep}{4pt}
\begin{tabular}{llccccccc}
\toprule
 & & \multicolumn{4}{c}{Pressure} & \multicolumn{3}{c}{Aneurysm-zone WSS} \\
\cmidrule(lr){3-6}\cmidrule(lr){7-9}
Case & Phase & \shortstack{Cont.\\field} & \shortstack{Steady\\PINN} & \shortstack{Unsteady\\PINN} & \shortstack{Unsteady PINN,\\steady form} & \shortstack{Cont.\\field} & \shortstack{Steady\\PINN} & \shortstack{Unsteady\\PINN} \\
\midrule
""" + body + r"""
\bottomrule
\end{tabular}
\end{table}
""", encoding="utf-8")
    print(body)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
