"""Sensitivity to near-wall observations: continuity field and RBF with and without observations
closer than Delta/2 = 1.25 mm to the wall (draw 0, 2.5 mm, Cases 2-8). Writes tables/nearwall.tex."""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
RUNS = ROOT / "report" / "metrics" / "reconstruction" / "runs"
OUT = ROOT / "paper" / "revision_2026_09" / "manuscript" / "tables" / "nearwall.tex"
MW = "_mw1.25"


def record(name: str) -> dict:
    path = RUNS / f"{name}.json"
    if not path.exists():
        raise FileNotFoundError(path)
    return json.loads(path.read_text())


def errors(r: dict) -> tuple[float, float, float]:
    return (r["velocity"]["vel_rel_l2"], r["pressure"]["unsteady+mut"]["p_rel_l2"], r["wss"]["wss_mag_rel_l2"])


def main() -> None:
    rows, audit = [], {}
    for t, phase in ((1780, "Systole"), (2400, "Diastole")):
        vals = {k: [] for k in ("cont", "rbf", "cont_mw", "rbf_mw")}
        for c in range(2, 9):
            cn = f"rev2_cont_oracle_c{c:02d}_t{t}_g2.5_s0_i0_w0.01"
            rn = f"rev2_rbf_c{c:02d}_t{t}_g2.5_s0"
            for k, n in (("cont", cn), ("rbf", rn), ("cont_mw", cn + MW), ("rbf_mw", rn + MW)):
                vals[k].append(errors(record(n)))
        med = {k: np.median(np.array(v), axis=0) for k, v in vals.items()}
        wins = [int(sum(a[i] < b[i] for a, b in zip(vals["cont_mw"], vals["rbf_mw"]))) for i in range(3)]
        audit[phase] = {"median": {k: m.tolist() for k, m in med.items()}, "cont_wins_without_nearwall": wins}
        for k, lab in (("cont", "Continuity field, all observations"), ("rbf", "RBF, all observations"),
                       ("cont_mw", "Continuity field, none within 1.25~mm"), ("rbf_mw", "RBF, none within 1.25~mm")):
            rows.append(f"{phase} & {lab} & " + " & ".join(f"{x:.3f}" for x in med[k]) + r" \\")
        if phase == "Systole":
            rows.append(r"\addlinespace")
    OUT.write_text(r"""% Generated by scripts/manuscript/generate_nearwall_table.py.
\begin{table}[htbp]
\centering
\small
\caption{Sensitivity to near-wall observations. Median relative errors over Cases~2--8 for draw 0 at $\Delta=2.5$~mm, with all observations and with the observations closer than $\Delta/2=1.25$~mm to the wall removed (28--32\% of them). Pressure uses the unsteady form with CFD eddy viscosity; WSS uses $h=0.25$~mm. Velocity is scored on all unobserved nodes, so the second pair of rows is also scored on the removed nodes.}
\label{tab:nearwall}
\begin{tabular}{llccc}
\toprule
Phase & Method and observations & Velocity & Pressure & WSS \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
""", encoding="utf-8")
    (ROOT / "report" / "tables").mkdir(parents=True, exist_ok=True)
    (ROOT / "report" / "tables" / "eacfm_nearwall.json").write_text(json.dumps(audit, indent=1))
    print(json.dumps(audit, indent=1))


if __name__ == "__main__":
    main()
